export const QUERY_KEYS = {
  USER: "user",
  USERS: "users",
  ORDERS: "orders",
  ORDER: "order",
  PRODUCTS: "products",
  PRODUCT: "product",
  INVENTORY_ITEMS: "inventoryItems",
  PRODUCT_REVIEWS: "productReviews",
  MENUS: "menus",
  MENU: "menu",
  TODAY_MENU: "todayMenu",
  CHARGE_HISTORY: "chargeHistory",
  NUMBER_OF_CUSTOMERS: "numberOfCustomers",
  REVENUE_STAT: "revenueStat",
  IMPORT_STAT: "importStat",
};
